# Pandas Revision

Syntax on `placement.csv`, practice on `food_orders.csv`.

In [45]:
import pandas as pd

p = pd.read_csv('/Users/ankit/BOX 1/B1 ROOM 1/AI&ML/class15/placement.csv')      # syntax examples
df = pd.read_csv('/Users/ankit/BOX 1/B1 ROOM 1/AI&ML/class15/food_orders.csv')  # practice

---
## 1. First look

In [46]:
# size: (rows, columns)
df.shape

(612, 13)

In [47]:
# numeric summary: count, mean, min, max
df.describe().round(2)

,order_hour,quantity,distance_km,order_value,delivery_time_min,rating,tip
count,612.00,612.00,604.00,612.00,612.00,505.00,427.00
mean,15.19,2.91,4.26,610.43,28.31,4.07,29.84
std,6.86,1.68,2.81,375.24,9.44,0.84,11.96
min,0.00,1.00,0.50,99.00,8.00,2.00,5.00
25%,13.00,2.00,2.20,326.25,22.00,4.00,20.00
50%,17.00,3.00,3.70,524.00,28.00,4.00,30.00
75%,20.00,4.00,5.70,794.00,34.00,5.00,40.00
max,23.00,8.00,14.00,2354.00,63.00,5.00,70.00

In [48]:
# column types and non-null counts
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 612 entries, 0 to 611
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   order_id           612 non-null    object
 1   city               612 non-null    object
 2   cuisine            612 non-null    object
 3   day                612 non-null    object
 4   order_hour         612 non-null    int64
 5   quantity           612 non-null    int64
 6   distance_km        604 non-null    float64
 7   order_value        612 non-null    int64
 8   delivery_time_min  612 non-null    int64
 9   payment            612 non-null    object
 10  rating             505 non-null    float64
 11  tip                427 non-null    float64
 12  was_late           612 non-null    object
dtypes: float64(3), int64(4), object(6)
memory usage: 62.3+ KB

### Practice

**Q1.** How many orders are in the file, and how many details are stored for each order?

In [49]:
# 612 orders and 13 details (columns)
df.shape

(612, 13)

**Q2.** Someone ordered food worth a small EMI. Find the biggest order value and the longest delivery time using one command.

In [50]:
# Biggest order value: 2354; longest delivery: 63 minutes
df[['order_value', 'delivery_time_min']].max()

order_value          2354
delivery_time_min      63
dtype: int64

**Q3.** Which columns hold numbers and which hold text?

In [51]:
numeric_columns = df.select_dtypes(include='number').columns.tolist()
text_columns = df.select_dtypes(include='object').columns.tolist()
print('Numeric columns:', numeric_columns)
print('Text columns:', text_columns)

Numeric columns: ['order_hour', 'quantity', 'distance_km', 'order_value', 'delivery_time_min', 'rating', 'tip']
Text columns: ['order_id', 'city', 'cuisine', 'day', 'payment', 'was_late']

---
## 2. Selecting

In [52]:
# one column
df['city']

0         Mumbai
1           Pune
2      Hyderabad
3          Delhi
4          Delhi
         ...
607         Pune
608    Bangalore
609       Mumbai
610         Pune
611    Bangalore
Name: city, Length: 612, dtype: object

In [53]:
# many columns: a list inside [ ]
df[['city', 'cuisine', 'order_value']].head()

        city   cuisine  order_value
0     Mumbai   Chinese          519
1       Pune   Chinese          295
2  Hyderabad   Chinese          744
3      Delhi  Desserts          370
4      Delhi    Burger          594

In [54]:
# iloc: by position -> rows, columns
df.iloc[0:5, 0:3]

   order_id       city   cuisine
0  ORD10591     Mumbai   Chinese
1  ORD10520       Pune   Chinese
2  ORD10588  Hyderabad   Chinese
3  ORD10113      Delhi  Desserts
4  ORD10322      Delhi    Burger

In [55]:
# loc: by label -> rows, column names (both ends included)
df.loc[0:4, 'city':'quantity']

        city   cuisine  day  order_hour  quantity
0     Mumbai   Chinese  Thu          22         3
1       Pune   Chinese  Sat          14         1
2  Hyderabad   Chinese  Sat          22         3
3      Delhi  Desserts  Mon          22         3
4      Delhi    Burger  Fri          14         4

### Practice

**Q4.** The manager's eyes hurt after 13 columns. Show only `city`, `cuisine` and `order_value` for the first 10 orders.

In [56]:
df.loc[:9, ['city', 'cuisine', 'order_value']]

        city       cuisine  order_value
0     Mumbai       Chinese          519
1       Pune       Chinese          295
2  Hyderabad       Chinese          744
3      Delhi      Desserts          370
4      Delhi        Burger          594
5     Mumbai       Biryani          933
6  Hyderabad  South Indian          197
7       Pune       Biryani         1482
8  Bangalore       Biryani          522
9       Pune  South Indian          233

**Q5.** The printer jammed and printed only rows 50 to 54, first 5 columns. Recreate that page using positions.

In [57]:
df.iloc[50:55, :5]

    order_id       city       cuisine  day  order_hour
50  ORD10161  Bangalore         Pizza  Sun          22
51  ORD10156       Pune      Desserts  Mon          21
52  ORD10160      Delhi      Desserts  Sat          20
53  ORD10310       Pune      Desserts  Sun          13
54  ORD10018     Mumbai  South Indian  Sat          18

**Q6.** Using labels, show rows 100 to 105 and every column from `city` to `order_hour`.

In [58]:
df.loc[100:105, 'city':'order_hour']

          city       cuisine  day  order_hour
100       Pune       Biryani  Sat          12
101       Pune        Burger  Sun          21
102     Mumbai         Pizza  Thu          17
103  Bangalore       Biryani  Sun          19
104     Mumbai         Pizza  Sun          23
105     Mumbai  South Indian  Sun          13

---
## 3. Filtering and sorting

In [59]:
# one condition
p[p['cgpa'] > 8]

,student_id,cgpa,twelfth_percent,branch,internships,projects,backlogs,prep_hours,communication_score,hostel,placed,package_lpa
14,VS2701,9.01,64.8,ECE,1.0,0,1,NaN,4.8,Yes,Yes,6.70
16,VS3012,8.29,77.8,CSE,0.0,2,0,81.0,7.9,Yes,Yes,8.06
17,VS2892,8.84,86.3,Civil,1.0,2,0,132.0,3.4,No,Yes,5.77
18,VS2936,8.23,69.5,CSE,3.0,3,1,119.0,6.9,Yes,Yes,8.54
21,VS2930,8.07,83.1,Mech,1.0,2,0,120.0,9.5,Yes,Yes,5.38
...,...,...,...,...,...,...,...,...,...,...,...,...
537,VS2668,8.21,74.2,CSE,0.0,4,0,157.0,5.5,Yes,Yes,7.66
539,VS2966,8.45,80.9,Mech,2.0,2,1,90.0,7.6,No,Yes,7.31
545,VS2811,8.40,79.7,ECE,1.0,4,0,173.0,5.0,Yes,Yes,6.22
548,VS2796,8.86,78.2,ECE,3.0,1,0,259.0,6.4,Yes,Yes,7.51
549,VS2775,8.45,70.7,CSE,0.0,3,0,NaN,5.1,Yes,Yes,8.45

In [60]:
# two conditions: & is and, | is or, each in its own ( )
p[(p['cgpa'] > 8) & (p['backlogs'] == 0)]

,student_id,cgpa,twelfth_percent,branch,internships,projects,backlogs,prep_hours,communication_score,hostel,placed,package_lpa
16,VS3012,8.29,77.8,CSE,0.0,2,0,81.0,7.9,Yes,Yes,8.06
17,VS2892,8.84,86.3,Civil,1.0,2,0,132.0,3.4,No,Yes,5.77
21,VS2930,8.07,83.1,Mech,1.0,2,0,120.0,9.5,Yes,Yes,5.38
44,VS3139,8.85,81.2,Mech,0.0,3,0,194.0,7.4,No,Yes,6.89
47,VS2788,8.09,84.6,Mech,0.0,2,0,220.0,6.0,Yes,No,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...
534,VS3112,8.37,63.9,CSE,4.0,2,0,103.0,5.9,Yes,Yes,7.52
537,VS2668,8.21,74.2,CSE,0.0,4,0,157.0,5.5,Yes,Yes,7.66
545,VS2811,8.40,79.7,ECE,1.0,4,0,173.0,5.0,Yes,Yes,6.22
548,VS2796,8.86,78.2,ECE,3.0,1,0,259.0,6.4,Yes,Yes,7.51
549,VS2775,8.45,70.7,CSE,0.0,3,0,NaN,5.1,Yes,Yes,8.45

In [61]:
# value is one of many
p[p['branch'].isin(['CSE', 'IT'])]

# value inside a range (both ends included)
p[p['cgpa'].between(7, 8)]

,student_id,cgpa,twelfth_percent,branch,internships,projects,backlogs,prep_hours,communication_score,hostel,placed,package_lpa
0,VS2821,7.41,78.5,IT,0.0,6,1,188.0,4.3,No,No,0.00
1,VS3068,7.52,70.0,CSE,2.0,3,0,167.0,9.8,Yes,Yes,10.06
2,VS2940,7.35,78.3,CSE,2.0,0,3,199.0,4.8,Yes,Yes,NaN
3,VS3138,7.86,60.2,CSE,1.0,3,0,135.0,8.0,No,Yes,8.63
6,VS2971,7.79,74.7,CSE,0.0,4,0,NaN,7.3,Yes,No,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...
536,VS3032,7.53,83.5,ECE,0.0,2,3,20.0,6.7,No,No,0.00
542,VS2998,7.81,63.4,IT,4.0,4,0,89.0,5.1,Yes,Yes,8.52
543,VS2785,7.19,77.5,ECE,3.0,4,0,84.0,6.5,No,Yes,6.68
544,VS2948,7.18,87.2,ECE,NaN,1,1,296.0,4.2,Yes,No,0.00
546,VS3102,7.60,76.5,Civil,0.0,4,0,NaN,6.7,Yes,Yes,5.68

In [62]:
# count of each category
p['branch'].value_counts()

branch
CSE      167
IT       118
ECE      112
Mech     103
Civil     50
Name: count, dtype: int64

In [63]:
# sort, biggest first
p.sort_values('cgpa', ascending=False).head()

,student_id,cgpa,twelfth_percent,branch,internships,projects,backlogs,prep_hours,communication_score,hostel,placed,package_lpa
113,VS3148,10.00,93.9,Mech,3.0,3,0,190.0,6.8,Yes,Yes,9.17
500,VS2917,10.00,84.0,ECE,0.0,4,0,58.0,6.3,No,Yes,8.54
265,VS2702,9.95,86.5,CSE,2.0,0,0,248.0,7.0,No,Yes,10.03
185,VS3124,9.85,63.8,CSE,0.0,4,0,87.0,7.5,Yes,Yes,8.77
157,VS2747,9.78,85.3,ECE,2.0,2,0,NaN,5.3,Yes,Yes,NaN

### Practice

**Q7.** Biryani at 2 AM is not hunger, it is a lifestyle. Count the Biryani orders placed between midnight and 3 AM (hours 0 to 3).

In [64]:
df[(df['order_hour'].between(0,3))&
   (df["cuisine"]=="Brryani")].shape[0]

df.head()

,order_id,city,cuisine,day,order_hour,quantity,distance_km,order_value,delivery_time_min,payment,rating,tip,was_late
0,ORD10591,Mumbai,Chinese,Thu,22,3,4.5,519,27,Card,NaN,15.0,No
1,ORD10520,Pune,Chinese,Sat,14,1,14.0,295,60,Cash,3.0,15.0,Yes
2,ORD10588,Hyderabad,Chinese,Sat,22,3,11.8,744,44,UPI,3.0,NaN,Yes
3,ORD10113,Delhi,Desserts,Mon,22,3,5.2,370,36,UPI,5.0,20.0,No
4,ORD10322,Delhi,Burger,Fri,14,4,7.2,594,29,UPI,5.0,10.0,No

**Q8.** Someone in Pune is clearly throwing a party. Show Pune orders worth more than 1000 rupees. How many?

In [65]:
df[(df["city"]=="pune")& df["order_value"]>1000].shape[0]

0

**Q9.** A food blogger survives only on Pizza and Burger. How many such orders are there?

In [73]:
df[(df["cuisine"]=='Pizza')& df["cuisine"]=="Burger"].count()

order_id             0
city                 0
cuisine              0
day                  0
order_hour           0
quantity             0
distance_km          0
order_value          0
delivery_time_min    0
payment              0
rating               0
tip                  0
was_late             0
dtype: int64

**Q10.** How many deliveries fell in the *"bhaiya, kahan ho?"* zone of 30 to 45 minutes?

In [71]:
df[(df["delivery_time_min"]>30)& df["delivery_time_min"]<45].shape[0]

612

**Q11.** Does anyone still pay in cash? Count the orders by payment method.

In [79]:
df[(df['payment']=='Cash')].shape[0]

95

**Q12.** Someone definitely ordered for the whole hostel. Show the 5 biggest orders with `city`, `cuisine`, `quantity` and `order_value`.

In [85]:
df.sort_values('order_value',ascending=False)[['city','cuisine','quantity']]

          city       cuisine  quantity
586  Hyderabad       Biryani         8
544  Hyderabad       Biryani         8
476     Mumbai       Biryani         8
367       Pune       Biryani         8
388  Hyderabad       Biryani         6
..         ...           ...       ...
247     Mumbai  South Indian         1
244  Hyderabad  South Indian         1
538     Mumbai  South Indian         1
489      Delhi  South Indian         1
43   Bangalore  South Indian         1

[612 rows x 3 columns]

**Q13.** Which delivery partners were basically The Flash? Show the 5 fastest deliveries with `city`, `distance_km` and `delivery_time_min`.

In [87]:
df.sort_values('delivery_time_min',ascending=True)[['city','distance_km','delivery_time_min']]

          city  distance_km  delivery_time_min
325       Pune          1.2                  8
580       Pune          1.4                  8
480      Delhi          1.0                  8
121  Hyderabad          1.3                  8
458      Delhi          1.4                  9
..         ...          ...                ...
102     Mumbai         10.2                 57
461  Hyderabad         14.0                 59
1         Pune         14.0                 60
54      Mumbai         14.0                 62
21   Bangalore         13.8                 63

[612 rows x 3 columns]

---
## 4. Cleaning

In [91]:
# blanks per column
p.isnull().sum()

student_id              0
cgpa                    0
twelfth_percent         0
branch                  0
internships            31
projects                0
backlogs                0
prep_hours             96
communication_score    12
hostel                  0
placed                  0
package_lpa            33
dtype: int64

In [96]:
# repeated rows
print(p.duplicated().sum())

# remove repeated rows
p_clean = df.drop_duplicates()

p.head()

0

,student_id,cgpa,twelfth_percent,branch,internships,projects,backlogs,prep_hours,communication_score,hostel,placed,package_lpa
0,VS2821,7.41,78.5,IT,0.0,6,1,188.0,4.3,No,No,0.00
1,VS3068,7.52,70.0,CSE,2.0,3,0,167.0,9.8,Yes,Yes,10.06
2,VS2940,7.35,78.3,CSE,2.0,0,3,199.0,4.8,Yes,Yes,NaN
3,VS3138,7.86,60.2,CSE,1.0,3,0,135.0,8.0,No,Yes,8.63
4,VS2670,5.63,88.3,CSE,2.0,2,0,132.0,6.3,No,Yes,5.22

In [97]:
# remove rows where one column is blank
p_clean = p_clean.dropna(subset=['internships'])

# fill blanks with a value
p_clean['prep_hours'] = p_clean['prep_hours'].fillna(0)

# change the type
p_clean['internships'] = p_clean['internships'].astype(int)

KeyError: ['internships']

In [94]:
# new column from existing columns
p_clean['cgpa_percent'] = (p_clean['cgpa'] * 9.5).round(1)
p_clean[['cgpa', 'cgpa_percent']].head()

NameError: name 'p_clean' is not defined

### Practice

**Q14.** Count the blanks in every column.

**Q15.** The app got confused and saved some orders twice. How many repeated rows are there?

**Q16.** Remove the repeated orders before customers get charged twice. Print the shape.

**Q17.** GPS failed for some orders, so the delivery partner took the scenic route. Remove the rows with a blank `distance_km` and print the shape.

**Q18.** A blank tip means no tip, and one sad delivery partner. Fill the blanks in `tip` with 0 and make it a whole number.

**Q19.** Add a column `value_per_item`: order value divided by quantity, rounded.

---
## 5. Grouping and saving

In [ ]:
# average per group
df.groupby('branch')['cgpa'].mean()

In [ ]:
# sorted, highest first
df.groupby('branch')['cgpa'].mean().sort_values(ascending=False)

In [ ]:
# other numbers per group
df.groupby('branch')['cgpa'].max()
df.groupby('branch')['internships'].sum()
df.groupby('branch')['student_id'].count()

In [ ]:
# save to a file, without the index column
df_clean.to_csv('placement_clean.csv', index=False)

### Practice

**Q20.** Which city is the stingiest tipper? Find the average tip per city, lowest first.

**Q21.** Is the weekend really a party? Find the average order value for each day, highest first.

**Q22.** Does a late delivery earn an angry rating? Compare the average rating of late and on-time orders.

**Q23.** Which city holds the record for the single biggest order after cleaning? Find the highest order value in each city.

**Q24.** Which payment method brings in the most money? Find the total order value for each payment method.

**Q25.** Which cuisine is the nation's favourite? Count the orders for each cuisine.

**Q26.** Save the cleaned data as `food_orders_clean.csv` without the index column.

---
*Q16 to Q19 change `food`. Run them only once, in order.*